### ISSUE TITLE
Handle Docker Compose files as YAML

### ISSUE THREAD

**Issue by maxexcloo** [bennycode/sort-everything#14]
Sort Everything is capable of sorting Docker Compose files when the filetype is set to YAML, would it be possible to add this as a default?

**Comment by maxexcloo** [comment]
Have created a PR: https://github.com/bennycode/sort-everything/pull/15

**Comment by bennycode** [comment]
Thanks for making the PR! With which filenames have you tested it? When using `docker-compose.yaml` it was working for me already as it is. Can you confirm that `textEditor.document.languageId` really returns `dockercompose`?

**Comment by maxexcloo** [comment]
I'm fairly certain! It hasn't been doing compose for me somehow unfortunately, have been setting the filetype manually every file open.

**Comment by maxexcloo** [comment]
Have tested and this has been working, any chance to merge?

**Comment by bennycode** [comment]
Yes, I will merge it and make a new release. Thank you very much for your contribution. 🥳

For reference: https://github.com/bennycode/sort-everything/pull/15

**Comment by maxexcloo** [comment]
Thank you 🤩

**Comment by bennycode** [comment]
Great, I released it with v1.4.1 🚀
